### ISSUE TITLE
Error in Clipart Dataset

### ISSUE THREAD

**Issue by xychen9459** [VisionLearningGroup/DA_Detection#5]
When I use `train_scripts/clipart_sample.sh` to train the network, terminal displays the following error message:

```
Appending horizontally-flipped training examples...
wrote gt roidb to ./DA_Detection/data/cache/clipart_trainval_gt_roidb.pkl
error
[ True False False False  True  True]
[[   27   137   157   181]
 [65445    66     4   163]
 [65470   192    78   254]
 [65439   372   138   483]
 [65273   190 65474   415]
 [65278   307 65416   371]]
300
done
Preparing training data...
done
before filtering, there are 2000 images...
after filtering, there are 2000 images...
33102 source roidb entries
2000 target roidb entries
```

It seems that the error messages comes from the annotation error in clipart dataset. Shall I need to throw the problematic image/annotation away from clipart dataset?

**Comment by kinredon** [comment]
It's not necessary for you to delete the problematic image/annotation away cause the number of problematic images/annotations is small. The deep model can accommodate the noise.
